name: nasmobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+4

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: ">=3.3.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  intl: ^0.19.0
  flutter_svg: ^2.0.17
  flutter_gemini: ^3.0.0
  lottie: ^3.2.0
  scrollable_positioned_list: ^0.3.8
  typewritertext: ^3.0.9
  chat_gpt_flutter: ^1.0.16
  google_maps_flutter: ^2.10.0
  dropdown_search: ^5.0.6
  syncfusion_flutter_datepicker: ^26.2.5
  flutter_slidable: ^3.1.2
  geolocator: ^13.0.4
  permission_handler: ^11.3.1
  widget_to_marker: ^1.0.6
  sqflite: ^2.4.1
  path: ^1.9.0
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.4
  dartz: ^0.10.1
  dio: ^5.8.0+1
  logger: ^2.5.0
  freezed_annotation: ^3.0.0
  panorama_viewer: ^2.0.2
  share_plus: ^11.0.0
  carousel_slider_plus: ^7.1.0
  flutter_rating_stars: ^1.1.0
  flutter_switch: ^0.3.2
  calendar_view: ^1.4.0
  image_picker: ^1.1.2
  syncfusion_flutter_charts: ^26.2.14
  geocoding: ^3.0.0
  map_launcher: ^3.5.0
  url_launcher: ^6.3.1
  camera: ^0.11.0+2
  image: ^4.3.0
  firebase_core: ^3.12.1
  animated_text_kit: ^4.2.3
  typewrite_text: ^1.0.3
  cloud_firestore: ^5.6.5
  path_provider: ^2.1.5
  device_calendar: ^4.3.3
  timezone: ^0.9.0 
  google_sign_in: ^6.2.2
  firebase_auth: ^5.5.1
  flutter_facebook_auth: ^7.1.1
  camerakit_flutter: ^1.0.5
  video_player: ^2.9.5
  flutter_html: ^3.0.0-beta.2
  http_parser: ^4.0.2
  flutter_widget_from_html: ^0.16.0
  flutter_otp_text_field: ^1.5.1+1
  pin_code_fields: ^8.0.1
  keyboard_actions: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.14.3

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

## Launcher icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/sql/
    - assets/tflite/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true
  class_name: S
  main_locale: vi_VN

