// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRmcAFe3pZIf5gL6og_P4AcvuF5euCGH0',
    appId: '1:174371785389:android:00ef7721c53c22ac781424',
    messagingSenderId: '174371785389',
    projectId: 'nas-app-service',
    storageBucket: 'nas-app-service.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHQi5qf3oQxotjhVv02VOpzBSWvPuEGnA',
    appId: '1:174371785389:ios:ab4af9095a2e9110781424',
    messagingSenderId: '174371785389',
    projectId: 'nas-app-service',
    storageBucket: 'nas-app-service.firebasestorage.app',
    androidClientId:
        '174371785389-j4m9njh6bdqkouiqibunl5p5jvooubu9.apps.googleusercontent.com',
    iosClientId:
        '174371785389-pm8a4972cqr90475onmfpgna6lnlv172.apps.googleusercontent.com',
    iosBundleId: 'com.nas.nasmobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnd3q0ZpkziTfRucsYN8u0iwgAccaV2lE',
    appId: '1:174371785389:web:471f0ca4ba66a21d781424',
    messagingSenderId: '174371785389',
    projectId: 'nas-app-service',
    authDomain: 'nas-app-service.firebaseapp.com',
    storageBucket: 'nas-app-service.firebasestorage.app',
    measurementId: 'G-BV1H2RB6E6',
  );
}
